#bashrc for psrsoft
HOME=/home/psr
PSRHOME=/home/psr/software
#For psrsoft
#For PGPLOT
export PGPLOT_DIR=/usr/lib/pgplot5
export PGPLOT_FONT=/usr/lib/pgplot5/grfont.dat
export PGPLOT_INCLUDES=/usr/include
export PGPLOT_BACKGROUND=white
export PGPLOT_FOREGROUND=black
export PGPLOT_DEV=/usr/bin/xs
#For PSRCAT
export PSRCAT_FILE=$PSRHOME/psrcat_tar/psrcat.db
#For TEMPO
export TEMPO=$PSRHOME/tempo

#For temopo2
export TEMPO2=$PSRHOME/tempo2


export PATH=$PATH:$PSRHOME/psrcat_tar:$PSRHOME/tempo/bin:$PSRHOME/psrchive/bin:$PSRHOME/tempo2/bin:$PSRHOME/calceph/bin

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PSRHOME/calceph/lib

export C_INCLUDE_PATH=$C_INCLUDE_PATH:$PSRHOME/calceph/include

export PYTHONPATH=$PYTHONPATH:$PSRHOME/psrchive/lib/python2.7/site-packages

